name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ vnext ]

jobs:
  Build:
    strategy:
      matrix:
        os: [windows-2019, windows-2022, ubuntu-24.04]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          sdkVersion: '1.3.261.1'
      - name: Test Environment
        shell: bash
        run: |
          echo "VULKAN_SDK=$VULKAN_SDK"
          echo "VULKAN_SDK_VERSION=$VULKAN_SDK_VERSION"
          echo "VK_LAYER_PATH=$VK_LAYER_PATH"
          echo "SWIFTSHADER_INSTALL_PATH=$SWIFTSHADER_INSTALL_PATH"
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
          echo "VK_DRIVER_FILES=$VK_DRIVER_FILES"
          echo "generated driver manifest:"
          cat $VK_DRIVER_FILES

          cmake -S test -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE="${{ github.workspace }}"
          cmake --build build --config Release
          ./vulkan-ci-test
